---
title: Implementing Reproducible Visualizations 
subtitle: "Application of coloring book technique in a reproducible ggplot2 system"
authors: 
- Andriy Koval
date: '2019-11-06'
event: "[Statistics & Data Science Colloquium Series](https://sciences.ucf.edu/statistics/events/)"
slug: []
categories:
  - functional graphing
  - reproducible research
  - statistical learning
tags:
  - logistic regression
  - ggplot2
  - coloring book
  - graphing techniques
  - hackathon
summary: ''
lastmod: '2019-11-07'
featured: no
image:
  caption: ''
  focal_point: 'Center'
  preview_only: no
projects: []
url_code: "https://github.com/andkov/ipdln-2018-hackathon"
url_dataset: "https://github.com/andkov/ipdln-2018-hackathon/blob/master/data-public/derived/technique-demonstration/ls_model.rds"
url_pdf: "2019-11-08-visualizing-logistic-regression-UCF-StatsDS-colloquium.pdf"
url_poster: ""
url_project: "functional-graphing"
url_slides: "2019-11-08-visualizing-logistic-regression-UCF-StatsDS-colloquium.pdf"
url_source: ""
url_video: ""
---

Visualising results of statistical modeling is a key component of data science workflow. Statistical graphs often is the best means to explain and promote research findings. However,in order to find that one graph that tells the story worth sharing, we sometimes have to try out and sift through many data visualizations. How should we approach such a task? What can we do to make it easier from both production and evaluation perspectives? This talk will demonstrate a reproducible graphing system designed for the IPDLN-2018 hackathon. 

The system evaluates synthetic socioeconomic and mortality data with logistic regression. The data was prepared for the hackathon by Statistic Canada and represents Canadian population. First, I will introduce a visualisation technique that uses color to create a meaningful expectations from the results of a logistic regression. Then I will discuss the workflow of the project that implements this graphing system ( github.com/andkov/ipdln-2018-hackathon ). I will conclude by building the case to prefer reproducible workflows with version control over computational notebooks (e.g. Jupyter, R Notebook).

