---
title: Visualizing Logistic Regression
subtitle: "Application of coloring book technique in a reproducible ggplot2 system"
authors: 
- Andriy Koval
date: '2018-11-01T16:00:00-07:00'
event: "[Power of Population Data Science Webinar](https://www.popdata.bc.ca/events/etu/PPDS_Webinars_2018_Nov1)"
slug: []
categories:
  - functional graphing
  - reproducible research
  - statistical learning
tags:
  - logistic regression
  - ggplot2
  - coloring book
  - graphing techniques
  - hackathon
  - IDPLN
summary: ''
lastmod: '2019-07-25T15:27:25-07:00'
featured: no
image:
  caption: ''
  focal_point: 'Center'
  preview_only: no
projects: []
url_code: "https://github.com/andkov/ipdln-2018-hackathon"
url_dataset: "https://github.com/andkov/ipdln-2018-hackathon/blob/master/data-public/derived/technique-demonstration/ls_model.rds"
url_pdf: "PopDataBC-webinar-coloring-book-2018-11-01.pdf"
url_poster: ""
url_project: "functional-graphing"
url_slides: "PopDataBC-webinar-coloring-book-2018-11-01.pdf"
url_source: ""
url_video: "https://www.youtube.com/embed/QtbhTu9HAzg"
---

Visualising results of statistical modeling is a key component of data science workflow. Statistical graphs are often the best means to explain and promote research findings.  However, in order to find that one graph that tells the story worth sharing, we sometimes have to try out and sift through many data visualizations. How should we approach such a task? What can we do to make it easier from both production and evaluation perspectives?

This presentation will demonstrate a reproducible graphing system designed for the  IPDLN-2018 hackathon. The system evaluates synthetic socioeconomic and mortality data with logistic regression. The data was prepared for the hackathon by Statistic Canada and represents Canadian population.

Topics covered will include:

- Introduction to a visualisation technique that uses color to create meaningful expectations from the results of a logistic regression.
- Details related to the workflow of the project that implements this graphing system (github.com/andkov/ipdln-2018-hackathon )
- Building the case for preference of reproducible workflows with version control over computational notebooks (e.g. Jupyter, R Notebook).

# Video
<iframe width="680" height="500" src="https://www.youtube.com/embed/QtbhTu9HAzg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

